# vim:set ft=dockerfile:
FROM redis:5.0.0

LABEL com.jogoj.service.name="redis" \
      com.jogoj.service.type="redis" \
      version="0.1" \
      description=""

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

EXPOSE 6379/tcp
